### ISSUE TITLE
[Project 2] Data set loading - out-of-memory error

### ISSUE THREAD

**Issue by ghost** [pbiecek/DataMning#35]
When I try to load 'smallLogs.rda' dataset R returns out-of-memory error. Is there any better way of loading the dataset than just using load("smallLogs.rda") function, which reads whole of it to the memory? Note that I have 4GB of memory available in my system.

**Comment by pbiecek** [comment]
Try this one: https://www.dropbox.com/s/jntva2xsong11st/verySmallLogs.rda?dl=0
It is 10 times smaller and uses only 300MB of memory.

**Comment by ghost** [comment]
Thank You, this one is working fine.
